### ISSUE TITLE
CUDAMatException

### ISSUE THREAD

**Issue by loveJasmine** [emansim/unsupervised-videos#12]
envy@ub1404:~/os_pri/github/unsupervised-videos$ python lstm_combo.py models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 1
invalid device ordinal
Traceback (most recent call last):
  File "lstm_combo.py", line 402, in <module>
    board = LockGPU(board=board_id)
  File "/home/envy/os_pri/github/unsupervised-videos/util.py", line 144, in LockGPU
    cm.cuda_set_device(board)
  File "/home/envy/os_pri/github/unsupervised-videos/cudamat/cudamat.py", line 2273, in cuda_set_device
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUDA error: no error
envy@ub1404:~/os_pri/github/unsupervised-videos$

**Comment by emansim** [comment]
I usually had this error when I ran out of memory on GPU.

Have you tried decreasing the size of the layer in LSTM ?

**Comment by loveJasmine** [comment]
which file i should change?

my gpu is gtx950M(4g)
I had done this, but not works yet:


envy@ub1404:~/os_pri/github/unsupervised-videos$ git diff
diff --git a/cudamat/Makefile b/cudamat/Makefile
index 0d4b76f..6759b00 100644
--- a/cudamat/Makefile
+++ b/cudamat/Makefile
@@ -1,7 +1,7 @@
 ##################################
 # Set path to dependencies.
 # CUDA.
-CUDA_ROOT=/pkgs/cuda-6.5
+CUDA_ROOT=/usr/local/cuda-7.5
 ###################################
 
 CUDA_LIB=$(CUDA_ROOT)/lib64
diff --git a/datasets/bouncing_mnist_valid.pbtxt b/datasets/bouncing_mnist_valid.pbtxt
index b157a1e..18bb90d 100644
--- a/datasets/bouncing_mnist_valid.pbtxt
+++ b/datasets/bouncing_mnist_valid.pbtxt
@@ -1,5 +1,5 @@
 dataset_type: VIDEO_PATCH
-data_file: "/ais/gobi3/u/emansim/unsupervised-videos/bouncing_mnist_test.npy"
+data_file: "/media/envy/data1t/dataset/bouncing_mnist_test.npy"
 num_frames: 20
 batch_size: 80
 image_size: 64
diff --git a/models/lstm_combo_1layer_mnist.pbtxt b/models/lstm_combo_1layer_mnist.pbtxt
index 30920d2..c25cc55 100644
--- a/models/lstm_combo_1layer_mnist.pbtxt
+++ b/models/lstm_combo_1layer_mnist.pbtxt
@@ -12,9 +12,9 @@ future_conditional: true
 binary_data: true
 lstm {
   name: "lstm_1_enc"
-  num_hid: 2048
+  num_hid: 512
   has_input: true
-  input_dims: 4096
+  input_dims: 1028
   w_dense {
     init_type: UNIFORM
     scale: 0.01
@@ -58,11 +58,11 @@ lstm {
 
 lstm_dec {
   name: "lstm_1_dec"
-  num_hid: 2048
+  num_hid: 512
   has_output: true
:
