### ISSUE TITLE
  invalid device function{cm.CUDAMatrix.init_random(42)}  cudamat.cudamat.CUDAMatException: CUDA error: no error

### ISSUE THREAD

**Issue by weihaoxie** [emansim/unsupervised-videos#15]
python lstm_combo.py models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 0
Using board 0
invalid device function
Traceback (most recent call last):
  File "lstm_combo.py", line 405, in <module>
    cm.CUDAMatrix.init_random(42)
  File "/home/weihaoxie/unsupervised-videos/cudamat/cudamat.py", line 382, in init_random
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUDA error: no error

**Comment by emansim** [comment]
Something wrong with cuda toolkit version or running out of memory on gpu.

We have only tried running it on cuda version 5.5 & 6.0

**Comment by yzxsunshine** [comment]
Hi, I somehow solved it by adding "-gencode=arch=compute_50,code=sm_50 \" in the makefile for cudamat. You can find it when assigning configuration strings to variable FLAG. The problem is caused by the mismatch between your cuda version and the configuration. My cuda7.5 works well after adding that line. Not sure whether it works for cuda 8.

**Comment by emansim** [comment]
Thanks @yzxsunshine !

**Comment by buaa-luzhi** [comment]
@yzxsunshine hello, My cuda8.0 encounter this problem.
I have already modify  "-gencode=arch=compute_50, code=sm_50 " in the makefile.  Still does not solve the problem.
Using board 0
invalid device function
Traceback (most recent call last):
File "lstm_combo.py", line 405, in 
cm.CUDAMatrix.init_random(42)
File "/home/weihaoxie/unsupervised-videos/cudamat/cudamat.py", line 382, in init_random
raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUDA error: no error
Do you know how to solve this problem.
Thank you very much!

**Comment by bottlecapper** [comment]
@emansim I come across the same problem! My cuda is 8.0
Using board 0
invalid device function
Traceback (most recent call last):
  File "/media/jg/D/Dropbox/JianTembine/Coding/Python/videoLSTM/lstm_combo.py", line 405, in <module>
    cm.CUDAMatrix.init_random(42)
  File "/media/jg/D/Dropbox/JianTembine/Coding/Python/videoLSTM/cudamat/cudamat.py", line 382, in init_random
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUDA error: no error
Process finished with exit code 1

Do you know how to fix it?

**Comment by buaa-luzhi** [comment]
@bottlecapper  sorry, I do not konw, maybe the version of cuda 8.0 is not  suitable. I haven't changed cuda yet. if you have some solutions, please tell me , Thank you very much!

**Comment by liaocs2008** [comment]
@buaa-luzhi Probably you have a nice GPU card requiring higher SM architecture. You may want to look for a suitable compilation setting. In general, here is a compilation to achieve maximum compatibility.
 
 -gencode=arch=compute_20,code=sm_20 \
 -gencode=arch=compute_30,code=sm_30 \
 -gencode=arch=compute_50,code=sm_50 \
 -gencode=arch=compute_52,code=sm_52 \
 -gencode=arch=compute_52,code=compute_52 \
 -gencode=arch=compute_60,code=sm_60 \
 -gencode=arch=compute_61,code=sm_61 \
 -gencode=arch=compute_62,code=sm_62 \

**Comment by abhinavkashyap92** [comment]
@liaocs2008 This one did the trick for me. For anyone using CUDA-8 use this (see whether the SM architecture that you specify in the makefile is compatible with the device that you have)

**Comment by jianghaojun** [comment]
@buaa-luzhi 
I had the same problem! My cuda is 8.0. 
I solved the problem by modifying below in the Makefile.
Thank you so much. @liaocs2008 

-gencode=arch=compute_20,code=sm_20 \
-gencode=arch=compute_30,code=sm_30 \
-gencode=arch=compute_35,code=sm_35 \
-gencode=arch=compute_50,code=sm_50 \
-gencode=arch=compute_52,code=sm_52 \
-gencode=arch=compute_60,code=sm_60 \
-gencode=arch=compute_61,code=sm_61 \
-gencode=arch=compute_62,code=sm_62 \

**Comment by DavidSUN2** [comment]
@buaa-luzhi have you solved this problem? I also modified Makefile, din't work. I used CUDA6.5. My Nvidia driver is Quadro FX 4800 whose computation capacity is 1.3. So, I add 
-gencode=arch=compute_13,code=sm_13. The error still occurred.

@abhinavkashyap92 How to tell whether the SM architecture that I specify in the makefile is compatible with the device that I have? Thanks.
