### ISSUE TITLE
How did you do Fprop?

### ISSUE THREAD

**Issue by liaocs2008** [emansim/unsupervised-videos#2]
Dear developers,

I am a newbie in LSTM so I read your code carefully to gain a deep understanding.

Basically, the code for Fprop runs like:
`for each batch:
    for each LSTM:
        LSTM.Fprop()`
where batch is the "input_frame" with shape (batch_size, input_dims) and LSTM units are stored in list "models_".

Let's take video patch as an example, i.e., "python lstm_combo.py models/lstm_combo_1layer_ucf101_patches.pbtxt datasets/ucf101_patches.pbtxt datasets/ucf101_patches_valid.pbtxt 1".

If you add print statements to show their shape or length, it outputs:
len(models_) = 1
input_frame= (100, 3072)

This means there is only one LSTM object in the "models_" list. Well, if you look at Fprop of LSTM class, it allocates memory for whole network, for example, "w_input_" variable.

My questions are:
1. Is each LSTM object a stacked LSTM network?
2. According to your LSTM Fprop implementation and your cuda kernel kLSTMFprop(), are you multiplying different "w" with "x" first and then in cuda kernel summing different components up?
3. Just to make sure, "ucf101_sample_train_patches.npy" has shape (9000, 20, 3, 32, 32) where 20 means 20 frames right? What is following code doing? 

`for t in xrange(self.enc_seq_length_):
   self.lstm_stack_enc_.Fprop(input_frame=self.v_.col_slice(t * self.num_dims_, (t+1) * self.num_dims_))`

Any help will be appreciated. Thanks

**Comment by emansim** [comment]
1. class LSTM specifies one layer of LSTM network, whereas class LSTMStack specifies a stack of different layers in the network.

2. I don't really understand your question. Maybe you can point out to specific lines in the code.

3. Yes, it is the length of the video which is 20 frames in this case.
And the following code slices a frame indexed t from the video and forward propagates it to LSTM.

**Comment by liaocs2008** [comment]
Thank you for your reply. I think I figured out most of you code these days. I have three more questions if you don't mind. 

Thanks in advance!

1. When I learn from online videos, they always draw LSTM unit connections like following:
...
  |          |            |
[u2] -> [u2'] -> [u2''] -> ...
  |          |            |
[u1] -> [u1'] -> [u1''] -> ...

But in your implementation, I can image their connections when your code multiply "s_in" with "w_dense". Are they fully connected like neural network, where depth is the dimension of time?


2. How to repeat your visualization experiment as shown in the paper? For example the "Fig 9", I can open the model file (hd5f), where there are "w_input", "w_output", "w_dense", "w_diag" and "w_b". But I don't know what do you mean in the paper, i.e., "Inputs", "Input Gates", "Forget Gates" and "Output Gates". They are all weights, right? How are they related to data stored in the model file?


3. Last but not least, I can understand the general formula of forward propagation of LSTM. Do you know where can I find details of both forward propagation and backward propagation formula? Especially when you use diagonal matrix for "W_c * C_{t-1}", I think I didn't learn it right.

Thanks for your time!
