### ISSUE TITLE
Request for the script to generate moving mnist video dataset

### ISSUE THREAD

**Issue by mathcbc** [emansim/unsupervised-videos#30]
Hi, would you mind to share the code for generating the moving mnist video dataset?

Thanks.

**Comment by mansimov** [comment]
yes take a look here https://github.com/emansim/unsupervised-videos/blob/master/data_handler.py#L334

more specifically take a look at ```GetRandomTrajectory``` function https://github.com/emansim/unsupervised-videos/blob/master/data_handler.py#L373
