### ISSUE TITLE
libcudamat_conv_gemm.so

### ISSUE THREAD

**Issue by chengchengjia** [emansim/unsupervised-videos#4]
Hi Emansim,

I try to train a model on MNIST dataset, but I cannot find libcudamat_conv_gemm.so.

Can you please help me to figure out what's happening?

Cheers,
Chengcheng
------------------------------------------------------------------------------------------------------------------------
python lstm_combo.py models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 0
Traceback (most recent call last):
  File "lstm_combo.py", line 1, in <module>
    from data_handler import *
  File "/home/smile/project/unsupervised-videos-master/data_handler.py", line 3, in <module>
    from util import *
  File "/home/smile/project/unsupervised-videos-master/util.py", line 4, in <module>
    from cudamat import cudamat_conv_gemm as cc
  File "/home/smile/project/unsupervised-videos-master/cudamat/cudamat_conv_gemm.py", line 4, in <module>
    _ConvNet = ct.cdll.LoadLibrary('libcudamat_conv_gemm.so')
  File "/home/smile/anaconda2/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/home/smile/anaconda2/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudamat_conv_gemm.so: cannot open shared object file: No such file or directory

**Comment by emansim** [comment]
you need to go first inside cudamat folder and install it by running "make"
make sure to set correct path to relevant dependencies inside Makefile

let me know if it helped .
I will make relevant changes to documentation

**Comment by chengchengjia** [comment]
Hi Elman,

Thanks, I have solved that problem and it can run now.

Bests,
Chengcheng

On Mon, Mar 14, 2016 at 1:47 AM, Elman Mansimov <notifications@github.com>
wrote:

> you need to go first inside cudamat folder and install it by running "make"
> make sure to set correct path to relevant dependencies inside Makefile
>
> let me know if it helped .
> I will make relevant changes to documentation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emansim/unsupervised-videos/issues/4#issuecomment-196153256>
> .
>



-- 
Best,
 Chengcheng Jia

PhD Student
Electrical and Computer Engineering,
Northeastern University,
Cell: 1-(857)320-9063
Email: jia.ch@husky.neu.edu
Personal Page: https://sites.google.com/site/chengchengjia128/

**Comment by chengchengjia** [comment]
Hi Elman,

I am trying to run my code by using your code, but I did not find the code
to generate feature (like ucf101). Could you share the code to generate
feature please? Thanks a lot.

Bests,
Chengcheng

On Mon, Mar 14, 2016 at 11:32 AM, Elman Mansimov <notifications@github.com>
wrote:

> Closed #4 <https://github.com/emansim/unsupervised-videos/issues/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emansim/unsupervised-videos/issues/4#event-588884868>.
>



-- 
Best,
 Chengcheng Jia

PhD Student
Electrical and Computer Engineering,
Northeastern University,
Cell: 1-(857)320-9063
Email: jia.ch@husky.neu.edu
Personal Page: https://sites.google.com/site/chengchengjia128/

**Comment by emansim** [comment]
You can use any popular software framework like caffe or Toronto ConvNet software https://github.com/TorontoDeepLearning/convnet in order to extract features.

You can then use lstm_classifier.py to do classification.

**Comment by chengchengjia** [comment]
Hi Elman,

I see. I will do it as suggested. Thanks a lot!

Bests,
Chengcheng

On Wed, Mar 16, 2016 at 1:32 PM, Elman Mansimov <notifications@github.com>
wrote:

> You can use any popular software framework like caffe or Toronto ConvNet
> software https://github.com/TorontoDeepLearning/convnet in order to
> extract features.
>
> You can then use lstm_classifier.py to do classification.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emansim/unsupervised-videos/issues/4#issuecomment-197445276>
>



-- 
Best,
 Chengcheng Jia

PhD Student
Electrical and Computer Engineering,
Northeastern University,
Cell: 1-(857)320-9063
Email: jia.ch@husky.neu.edu
Personal Page: https://sites.google.com/site/chengchengjia128/
