### ISSUE TITLE
cudamat.cudamat.CUDAMatException: CUDA error: no error

### ISSUE THREAD

**Issue by YantianZha** [emansim/unsupervised-videos#6]
Hi,

I met a problem and want to ask for your help.

I'm using: 
ubuntu 14.04
Cuda: 7.5
NVIDIA-Gpu: Quadro K2100M

![screenshot from 2016-03-21 15 26 06](https://cloud.githubusercontent.com/assets/9017839/13936214/5a87060e-ef79-11e5-930a-38ffe2ea3001.png)

Thanks very much!

**Comment by emansim** [comment]
I have never tested the code on any cudamat version beyond 6.5 , but there is no reason for it not to work.

There is an error in the cudaSetDevice function. How many boards do you have ? What if you comment that line and run your code ?

**Comment by YantianZha** [comment]
Sorry for the late reply. There's a new confusing error:
![screenshot from 2016-03-29 12 12 37](https://cloud.githubusercontent.com/assets/9017839/14120436/b2f28e56-f5a7-11e5-89f4-4a6da584fd3b.png)

Here is the script parameters: models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 1

I suspect there's a problem in the file "models/lstm_combo_1layer_mnist.pbtxt" ?

Thanks!

**Comment by springzfx** [comment]
According default model config, the resident GPU-Memory is about 728M, and  memory for computation is not included. You can try to reduce the model, for example changing hidden-units number from 2048 to 1000.

My running environment: Geforce GTX 960、Ubuntu 14.04
GPU utilization screenshot when running this code:
![cap1](https://cloud.githubusercontent.com/assets/8992037/14282438/f217dacc-fb70-11e5-8cd0-07acdf2846fd.png)
It takes about 98% of my 4G GPU-memory!!!

similar issue: [https://github.com/nitishsrivastava/deepnet/issues/69](url)

**Comment by smallflyingpig** [comment]
@YantianZha hi, I meet the same problem as you, have you solve this problem?

**Comment by YantianZha** [comment]
I'm sorry I haven't directly solved this problem. I upgraded my GPU.
