### ISSUE TITLE
Problem about moving MNIST

### ISSUE THREAD

**Issue by springzfx** [emansim/unsupervised-videos#8]
##  bounce-off problem 
digit moving is in fact based on **digit patch**(28\*28), not digit itself. So the bounce-off is exactly based on digit patch. In most case, digit will bounce back before digit arrives at the edge of outer box(64\*64) ,due to white padding in digit patch. 
Does it matter for the training? What problem will it cause?

##  digit overlap problem 
data_handler.py about line 417
```python
    """ Put b on top of a."""
   def Overlap(self, a, b):
    # S1: original by author, can not make sure that b is on top of a
    #return np.maximum(a, b)

    #S2: digit patch overlap,consistent  with bounce-off process 
    #return b

    # S3: digit overlap, but inconsistent with bounce-off process
    return np.where(b==0,a,b)
```
As mentioned by the notes above,

- S3 is truly **digit** overlap
- S2 is **digit patch** overlap
- S1 is something else, but it is the original code  in the project

Is that a problem?

**Comment by emansim** [comment]
I don't think that it will matter for training.

We don't have any information on where exactly the digit located in the patch and figuring it out will introduce more complexity into the code.

But even if you bounce off exactly based on the digit not based on the patch I don't think you would get drastically different results.
